//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DataPageField1 {
    
    private string dataPageFieldField;
    
    private string dataPageFieldLabelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageField {
        get {
            return this.dataPageFieldField;
        }
        set {
            this.dataPageFieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageFieldLabel {
        get {
            return this.dataPageFieldLabelField;
        }
        set {
            this.dataPageFieldLabelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DataPageField2 {
    
    private string dataPageFieldField;
    
    private string dataPageFieldLabelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageField {
        get {
            return this.dataPageFieldField;
        }
        set {
            this.dataPageFieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageFieldLabel {
        get {
            return this.dataPageFieldLabelField;
        }
        set {
            this.dataPageFieldLabelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DataPageField3 {
    
    private string dataPageFieldField;
    
    private string dataPageFieldLabelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageField {
        get {
            return this.dataPageFieldField;
        }
        set {
            this.dataPageFieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageFieldLabel {
        get {
            return this.dataPageFieldLabelField;
        }
        set {
            this.dataPageFieldLabelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Profile {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataPageField1", typeof(DataPageField1))]
    [System.Xml.Serialization.XmlElementAttribute("DataPageField2", typeof(DataPageField2))]
    [System.Xml.Serialization.XmlElementAttribute("DataPageField3", typeof(DataPageField3))]
    [System.Xml.Serialization.XmlElementAttribute("Settings", typeof(ProfileSettings), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettings {
    
    private string msgToneField;
    
    private string msgVibrateField;
    
    private string keyToneField;
    
    private string backlightTimeoutField;
    
    private string autoLightField;
    
    private string mapOrientationField;
    
    private string autoZoomField;
    
    private string goToLineField;
    
    private string mapPointsZoomField;
    
    private string waypointsZoomField;
    
    private string marineColorsField;
    
    private string trackRecordMethodField;
    
    private string trackIntervalField;
    
    private string ultraTracIntervalField;
    
    private string autoStartField;
    
    private string autoSaveField;
    
    private string autoPauseField;
    
    private string anchorDragField;
    
    private string anchorDragDistField;
    
    private string offCourseField;
    
    private string offCourseDistField;
    
    private string timeFormatField;
    
    private string dstModeField;
    
    private string otherTimeZoneField;
    
    private string timeZoneField;
    
    private string distanceUnitsField;
    
    private string elevationUnitsField;
    
    private string depthUnitsField;
    
    private string temperatureUnitsField;
    
    private string pressureUnitsField;
    
    private string sensorModeField;
    
    private string headingDisplayField;
    
    private string northReferenceField;
    
    private string magneticVariationField;
    
    private string compassField;
    
    private string compassAutoswitchField;
    
    private string altimeterAutoCalAdvField;
    
    private string barometerModeField;
    
    private string altimeterPlotTypeField;
    
    private string uGridCatField;
    
    private string uGridSubCatField;
    
    private string uGridFEField;
    
    private string uGridFNField;
    
    private string uGridK0Field;
    
    private string uGridLonoField;
    
    private string uGridFld7Field;
    
    private string uGridFld8Field;
    
    private string uGridFld9Field;
    
    private string uGridLatPt2Field;
    
    private string uGridLonPt2Field;
    
    private string uDatumDFField;
    
    private string uDatumDAField;
    
    private string uDatumDXField;
    
    private string uDatumDYField;
    
    private string uDatumDZField;
    
    private string posnFormatField;
    
    private string datumIdxField;
    
    private string spheroidIdxField;
    
    private string symbolGroupField;
    
    private string hRSensorEnabledField;
    
    private string cadenceSensorEnabledField;
    
    private string tempeEnabledField;
    
    private string chirpSearchingEnabledField;
    
    private string holdUpKeyField;
    
    private string holdDownKeyField;
    
    private string dataPageBackKeyField;
    
    private string dataPageUpKeyField;
    
    private string dataPageDownKeyField;
    
    private string proxAlertNotificationField;
    
    private string timePageLayoutField;
    
    private string secondsStyleField;
    
    private string timePageDataField;
    
    private string timePageIconsField;
    
    private string fitProfileAgeField;
    
    private string fitProfileHeightField;
    
    private string fitProfileWeightField;
    
    private string fitProfileGenderField;
    
    private string fitProfileLifeAthleteField;
    
    private string fitProfileHRZone1Field;
    
    private string fitProfileHRZone2Field;
    
    private string fitProfileHRZone3Field;
    
    private string fitProfileHRZone4Field;
    
    private string fitProfileHRZone5Field;
    
    private string fitProfileMaxHRField;
    
    private string fitProfileAutoLapField;
    
    private string fitProfileAutoLapDistField;
    
    private string fITActivityField;
    
    private string fileOutputGPXField;
    
    private string fileOutputFITField;
    
    private string compassPrimaryLettersField;
    
    private string trainingIndoorsField;
    
    private string footPodField;
    
    private string userWrittenField;
    
    private string autoAddFitHistoryField;
    
    private string foodPodCalFactorField;
    
    private ProfileSettingsMainMenuMmItem[] mainMenuField;
    
    private ProfileSettingsDistIntervalAlert[] distIntervalAlertField;
    
    private ProfileSettingsDistDestinationAlert[] distDestinationAlertField;
    
    private ProfileSettingsDistOffCourseAlert[] distOffCourseAlertField;
    
    private ProfileSettingsSpeedMinAlert[] speedMinAlertField;
    
    private ProfileSettingsSpeedMaxAlert[] speedMaxAlertField;
    
    private ProfileSettingsTimeIntervalAlert[] timeIntervalAlertField;
    
    private ProfileSettingsTimeSunsetAlert[] timeSunsetAlertField;
    
    private ProfileSettingsTimeETAAlert[] timeETAAlertField;
    
    private ProfileSettingsElevMinAlert[] elevMinAlertField;
    
    private ProfileSettingsElevMaxAlert[] elevMaxAlertField;
    
    private ProfileSettingsElevAscentAlert[] elevAscentAlertField;
    
    private ProfileSettingsElevDescentAlert[] elevDescentAlertField;
    
    private ProfileSettingsNavArrivalPointsAlert[] navArrivalPointsAlertField;
    
    private ProfileSettingsNavArrivalTracksAlert[] navArrivalTracksAlertField;
    
    private ProfileSettingsNavArrivalRoutesAlert[] navArrivalRoutesAlertField;
    
    private ProfileSettingsPaceMinAlert[] paceMinAlertField;
    
    private ProfileSettingsPaceMaxAlert[] paceMaxAlertField;
    
    private ProfileSettingsHRMinAlert[] hRMinAlertField;
    
    private ProfileSettingsHRMaxAlert[] hRMaxAlertField;
    
    private ProfileSettingsHRZoneAlert[] hRZoneAlertField;
    
    private ProfileSettingsCadMinAlert[] cadMinAlertField;
    
    private ProfileSettingsCadMaxAlert[] cadMaxAlertField;
    
    private ProfileSettingsBattPercentAlert[] battPercentAlertField;
    
    private ProfileSettingsDataPage[] dataPageField;
    
    private ProfileSettingsNavDataPage[] navDataPageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MsgTone {
        get {
            return this.msgToneField;
        }
        set {
            this.msgToneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MsgVibrate {
        get {
            return this.msgVibrateField;
        }
        set {
            this.msgVibrateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KeyTone {
        get {
            return this.keyToneField;
        }
        set {
            this.keyToneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BacklightTimeout {
        get {
            return this.backlightTimeoutField;
        }
        set {
            this.backlightTimeoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoLight {
        get {
            return this.autoLightField;
        }
        set {
            this.autoLightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MapOrientation {
        get {
            return this.mapOrientationField;
        }
        set {
            this.mapOrientationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoZoom {
        get {
            return this.autoZoomField;
        }
        set {
            this.autoZoomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GoToLine {
        get {
            return this.goToLineField;
        }
        set {
            this.goToLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MapPointsZoom {
        get {
            return this.mapPointsZoomField;
        }
        set {
            this.mapPointsZoomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WaypointsZoom {
        get {
            return this.waypointsZoomField;
        }
        set {
            this.waypointsZoomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MarineColors {
        get {
            return this.marineColorsField;
        }
        set {
            this.marineColorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TrackRecordMethod {
        get {
            return this.trackRecordMethodField;
        }
        set {
            this.trackRecordMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TrackInterval {
        get {
            return this.trackIntervalField;
        }
        set {
            this.trackIntervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UltraTracInterval {
        get {
            return this.ultraTracIntervalField;
        }
        set {
            this.ultraTracIntervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoStart {
        get {
            return this.autoStartField;
        }
        set {
            this.autoStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoSave {
        get {
            return this.autoSaveField;
        }
        set {
            this.autoSaveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoPause {
        get {
            return this.autoPauseField;
        }
        set {
            this.autoPauseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnchorDrag {
        get {
            return this.anchorDragField;
        }
        set {
            this.anchorDragField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AnchorDragDist {
        get {
            return this.anchorDragDistField;
        }
        set {
            this.anchorDragDistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OffCourse {
        get {
            return this.offCourseField;
        }
        set {
            this.offCourseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OffCourseDist {
        get {
            return this.offCourseDistField;
        }
        set {
            this.offCourseDistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimeFormat {
        get {
            return this.timeFormatField;
        }
        set {
            this.timeFormatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DstMode {
        get {
            return this.dstModeField;
        }
        set {
            this.dstModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OtherTimeZone {
        get {
            return this.otherTimeZoneField;
        }
        set {
            this.otherTimeZoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimeZone {
        get {
            return this.timeZoneField;
        }
        set {
            this.timeZoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DistanceUnits {
        get {
            return this.distanceUnitsField;
        }
        set {
            this.distanceUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ElevationUnits {
        get {
            return this.elevationUnitsField;
        }
        set {
            this.elevationUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DepthUnits {
        get {
            return this.depthUnitsField;
        }
        set {
            this.depthUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TemperatureUnits {
        get {
            return this.temperatureUnitsField;
        }
        set {
            this.temperatureUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PressureUnits {
        get {
            return this.pressureUnitsField;
        }
        set {
            this.pressureUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SensorMode {
        get {
            return this.sensorModeField;
        }
        set {
            this.sensorModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HeadingDisplay {
        get {
            return this.headingDisplayField;
        }
        set {
            this.headingDisplayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NorthReference {
        get {
            return this.northReferenceField;
        }
        set {
            this.northReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MagneticVariation {
        get {
            return this.magneticVariationField;
        }
        set {
            this.magneticVariationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Compass {
        get {
            return this.compassField;
        }
        set {
            this.compassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompassAutoswitch {
        get {
            return this.compassAutoswitchField;
        }
        set {
            this.compassAutoswitchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AltimeterAutoCalAdv {
        get {
            return this.altimeterAutoCalAdvField;
        }
        set {
            this.altimeterAutoCalAdvField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BarometerMode {
        get {
            return this.barometerModeField;
        }
        set {
            this.barometerModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AltimeterPlotType {
        get {
            return this.altimeterPlotTypeField;
        }
        set {
            this.altimeterPlotTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridCat {
        get {
            return this.uGridCatField;
        }
        set {
            this.uGridCatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridSubCat {
        get {
            return this.uGridSubCatField;
        }
        set {
            this.uGridSubCatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridFE {
        get {
            return this.uGridFEField;
        }
        set {
            this.uGridFEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridFN {
        get {
            return this.uGridFNField;
        }
        set {
            this.uGridFNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridK0 {
        get {
            return this.uGridK0Field;
        }
        set {
            this.uGridK0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridLono {
        get {
            return this.uGridLonoField;
        }
        set {
            this.uGridLonoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridFld7 {
        get {
            return this.uGridFld7Field;
        }
        set {
            this.uGridFld7Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridFld8 {
        get {
            return this.uGridFld8Field;
        }
        set {
            this.uGridFld8Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridFld9 {
        get {
            return this.uGridFld9Field;
        }
        set {
            this.uGridFld9Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridLatPt2 {
        get {
            return this.uGridLatPt2Field;
        }
        set {
            this.uGridLatPt2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UGridLonPt2 {
        get {
            return this.uGridLonPt2Field;
        }
        set {
            this.uGridLonPt2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UDatumDF {
        get {
            return this.uDatumDFField;
        }
        set {
            this.uDatumDFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UDatumDA {
        get {
            return this.uDatumDAField;
        }
        set {
            this.uDatumDAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UDatumDX {
        get {
            return this.uDatumDXField;
        }
        set {
            this.uDatumDXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UDatumDY {
        get {
            return this.uDatumDYField;
        }
        set {
            this.uDatumDYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UDatumDZ {
        get {
            return this.uDatumDZField;
        }
        set {
            this.uDatumDZField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PosnFormat {
        get {
            return this.posnFormatField;
        }
        set {
            this.posnFormatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DatumIdx {
        get {
            return this.datumIdxField;
        }
        set {
            this.datumIdxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpheroidIdx {
        get {
            return this.spheroidIdxField;
        }
        set {
            this.spheroidIdxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SymbolGroup {
        get {
            return this.symbolGroupField;
        }
        set {
            this.symbolGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HRSensorEnabled {
        get {
            return this.hRSensorEnabledField;
        }
        set {
            this.hRSensorEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CadenceSensorEnabled {
        get {
            return this.cadenceSensorEnabledField;
        }
        set {
            this.cadenceSensorEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TempeEnabled {
        get {
            return this.tempeEnabledField;
        }
        set {
            this.tempeEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChirpSearchingEnabled {
        get {
            return this.chirpSearchingEnabledField;
        }
        set {
            this.chirpSearchingEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HoldUpKey {
        get {
            return this.holdUpKeyField;
        }
        set {
            this.holdUpKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HoldDownKey {
        get {
            return this.holdDownKeyField;
        }
        set {
            this.holdDownKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageBackKey {
        get {
            return this.dataPageBackKeyField;
        }
        set {
            this.dataPageBackKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageUpKey {
        get {
            return this.dataPageUpKeyField;
        }
        set {
            this.dataPageUpKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageDownKey {
        get {
            return this.dataPageDownKeyField;
        }
        set {
            this.dataPageDownKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProxAlertNotification {
        get {
            return this.proxAlertNotificationField;
        }
        set {
            this.proxAlertNotificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimePageLayout {
        get {
            return this.timePageLayoutField;
        }
        set {
            this.timePageLayoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SecondsStyle {
        get {
            return this.secondsStyleField;
        }
        set {
            this.secondsStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimePageData {
        get {
            return this.timePageDataField;
        }
        set {
            this.timePageDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimePageIcons {
        get {
            return this.timePageIconsField;
        }
        set {
            this.timePageIconsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileAge {
        get {
            return this.fitProfileAgeField;
        }
        set {
            this.fitProfileAgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileHeight {
        get {
            return this.fitProfileHeightField;
        }
        set {
            this.fitProfileHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileWeight {
        get {
            return this.fitProfileWeightField;
        }
        set {
            this.fitProfileWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileGender {
        get {
            return this.fitProfileGenderField;
        }
        set {
            this.fitProfileGenderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileLifeAthlete {
        get {
            return this.fitProfileLifeAthleteField;
        }
        set {
            this.fitProfileLifeAthleteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileHRZone1 {
        get {
            return this.fitProfileHRZone1Field;
        }
        set {
            this.fitProfileHRZone1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileHRZone2 {
        get {
            return this.fitProfileHRZone2Field;
        }
        set {
            this.fitProfileHRZone2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileHRZone3 {
        get {
            return this.fitProfileHRZone3Field;
        }
        set {
            this.fitProfileHRZone3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileHRZone4 {
        get {
            return this.fitProfileHRZone4Field;
        }
        set {
            this.fitProfileHRZone4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileHRZone5 {
        get {
            return this.fitProfileHRZone5Field;
        }
        set {
            this.fitProfileHRZone5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileMaxHR {
        get {
            return this.fitProfileMaxHRField;
        }
        set {
            this.fitProfileMaxHRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileAutoLap {
        get {
            return this.fitProfileAutoLapField;
        }
        set {
            this.fitProfileAutoLapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FitProfileAutoLapDist {
        get {
            return this.fitProfileAutoLapDistField;
        }
        set {
            this.fitProfileAutoLapDistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FITActivity {
        get {
            return this.fITActivityField;
        }
        set {
            this.fITActivityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileOutputGPX {
        get {
            return this.fileOutputGPXField;
        }
        set {
            this.fileOutputGPXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileOutputFIT {
        get {
            return this.fileOutputFITField;
        }
        set {
            this.fileOutputFITField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompassPrimaryLetters {
        get {
            return this.compassPrimaryLettersField;
        }
        set {
            this.compassPrimaryLettersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TrainingIndoors {
        get {
            return this.trainingIndoorsField;
        }
        set {
            this.trainingIndoorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FootPod {
        get {
            return this.footPodField;
        }
        set {
            this.footPodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserWritten {
        get {
            return this.userWrittenField;
        }
        set {
            this.userWrittenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoAddFitHistory {
        get {
            return this.autoAddFitHistoryField;
        }
        set {
            this.autoAddFitHistoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FoodPodCalFactor {
        get {
            return this.foodPodCalFactorField;
        }
        set {
            this.foodPodCalFactorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("MmItem", typeof(ProfileSettingsMainMenuMmItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsMainMenuMmItem[] MainMenu {
        get {
            return this.mainMenuField;
        }
        set {
            this.mainMenuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DistIntervalAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsDistIntervalAlert[] DistIntervalAlert {
        get {
            return this.distIntervalAlertField;
        }
        set {
            this.distIntervalAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DistDestinationAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsDistDestinationAlert[] DistDestinationAlert {
        get {
            return this.distDestinationAlertField;
        }
        set {
            this.distDestinationAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DistOffCourseAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsDistOffCourseAlert[] DistOffCourseAlert {
        get {
            return this.distOffCourseAlertField;
        }
        set {
            this.distOffCourseAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SpeedMinAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsSpeedMinAlert[] SpeedMinAlert {
        get {
            return this.speedMinAlertField;
        }
        set {
            this.speedMinAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SpeedMaxAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsSpeedMaxAlert[] SpeedMaxAlert {
        get {
            return this.speedMaxAlertField;
        }
        set {
            this.speedMaxAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TimeIntervalAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsTimeIntervalAlert[] TimeIntervalAlert {
        get {
            return this.timeIntervalAlertField;
        }
        set {
            this.timeIntervalAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TimeSunsetAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsTimeSunsetAlert[] TimeSunsetAlert {
        get {
            return this.timeSunsetAlertField;
        }
        set {
            this.timeSunsetAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TimeETAAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsTimeETAAlert[] TimeETAAlert {
        get {
            return this.timeETAAlertField;
        }
        set {
            this.timeETAAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElevMinAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsElevMinAlert[] ElevMinAlert {
        get {
            return this.elevMinAlertField;
        }
        set {
            this.elevMinAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElevMaxAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsElevMaxAlert[] ElevMaxAlert {
        get {
            return this.elevMaxAlertField;
        }
        set {
            this.elevMaxAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElevAscentAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsElevAscentAlert[] ElevAscentAlert {
        get {
            return this.elevAscentAlertField;
        }
        set {
            this.elevAscentAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElevDescentAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsElevDescentAlert[] ElevDescentAlert {
        get {
            return this.elevDescentAlertField;
        }
        set {
            this.elevDescentAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NavArrivalPointsAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsNavArrivalPointsAlert[] NavArrivalPointsAlert {
        get {
            return this.navArrivalPointsAlertField;
        }
        set {
            this.navArrivalPointsAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NavArrivalTracksAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsNavArrivalTracksAlert[] NavArrivalTracksAlert {
        get {
            return this.navArrivalTracksAlertField;
        }
        set {
            this.navArrivalTracksAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NavArrivalRoutesAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsNavArrivalRoutesAlert[] NavArrivalRoutesAlert {
        get {
            return this.navArrivalRoutesAlertField;
        }
        set {
            this.navArrivalRoutesAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PaceMinAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsPaceMinAlert[] PaceMinAlert {
        get {
            return this.paceMinAlertField;
        }
        set {
            this.paceMinAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PaceMaxAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsPaceMaxAlert[] PaceMaxAlert {
        get {
            return this.paceMaxAlertField;
        }
        set {
            this.paceMaxAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HRMinAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsHRMinAlert[] HRMinAlert {
        get {
            return this.hRMinAlertField;
        }
        set {
            this.hRMinAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HRMaxAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsHRMaxAlert[] HRMaxAlert {
        get {
            return this.hRMaxAlertField;
        }
        set {
            this.hRMaxAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HRZoneAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsHRZoneAlert[] HRZoneAlert {
        get {
            return this.hRZoneAlertField;
        }
        set {
            this.hRZoneAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CadMinAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsCadMinAlert[] CadMinAlert {
        get {
            return this.cadMinAlertField;
        }
        set {
            this.cadMinAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CadMaxAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsCadMaxAlert[] CadMaxAlert {
        get {
            return this.cadMaxAlertField;
        }
        set {
            this.cadMaxAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BattPercentAlert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsBattPercentAlert[] BattPercentAlert {
        get {
            return this.battPercentAlertField;
        }
        set {
            this.battPercentAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataPage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsDataPage[] DataPage {
        get {
            return this.dataPageField;
        }
        set {
            this.dataPageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NavDataPage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfileSettingsNavDataPage[] NavDataPage {
        get {
            return this.navDataPageField;
        }
        set {
            this.navDataPageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsMainMenuMmItem {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsDistIntervalAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    private string unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsDistDestinationAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    private string unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsDistOffCourseAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    private string unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsSpeedMinAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    private string unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsSpeedMaxAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    private string unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsTimeIntervalAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string timeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsTimeSunsetAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string timeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsTimeETAAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string timeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsElevMinAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    private string unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsElevMaxAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    private string unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsElevAscentAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    private string unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsElevDescentAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    private string unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsNavArrivalPointsAlert {
    
    private string setField;
    
    private string notificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsNavArrivalTracksAlert {
    
    private string setField;
    
    private string notificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsNavArrivalRoutesAlert {
    
    private string setField;
    
    private string notificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsPaceMinAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string timeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsPaceMaxAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string timeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsHRMinAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsHRMaxAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsHRZoneAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsCadMinAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsCadMaxAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsBattPercentAlert {
    
    private string activeField;
    
    private string setField;
    
    private string notificationField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Set {
        get {
            return this.setField;
        }
        set {
            this.setField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Notification {
        get {
            return this.notificationField;
        }
        set {
            this.notificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsDataPage {
    
    private string dataPageTypeField;
    
    private string dataPageNameField;
    
    private string dataPageIdxField;
    
    private string dataPageCustomIdxField;
    
    private DataPageField1[] dataPageField1Field;
    
    private DataPageField2[] dataPageField2Field;
    
    private DataPageField3[] dataPageField3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageType {
        get {
            return this.dataPageTypeField;
        }
        set {
            this.dataPageTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageName {
        get {
            return this.dataPageNameField;
        }
        set {
            this.dataPageNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageIdx {
        get {
            return this.dataPageIdxField;
        }
        set {
            this.dataPageIdxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageCustomIdx {
        get {
            return this.dataPageCustomIdxField;
        }
        set {
            this.dataPageCustomIdxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataPageField1")]
    public DataPageField1[] DataPageField1 {
        get {
            return this.dataPageField1Field;
        }
        set {
            this.dataPageField1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataPageField2")]
    public DataPageField2[] DataPageField2 {
        get {
            return this.dataPageField2Field;
        }
        set {
            this.dataPageField2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataPageField3")]
    public DataPageField3[] DataPageField3 {
        get {
            return this.dataPageField3Field;
        }
        set {
            this.dataPageField3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfileSettingsNavDataPage {
    
    private string dataPageTypeField;
    
    private string dataPageNameField;
    
    private string dataPageIdxField;
    
    private string dataPageCustomIdxField;
    
    private DataPageField1[] dataPageField1Field;
    
    private DataPageField2[] dataPageField2Field;
    
    private DataPageField3[] dataPageField3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageType {
        get {
            return this.dataPageTypeField;
        }
        set {
            this.dataPageTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageName {
        get {
            return this.dataPageNameField;
        }
        set {
            this.dataPageNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageIdx {
        get {
            return this.dataPageIdxField;
        }
        set {
            this.dataPageIdxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataPageCustomIdx {
        get {
            return this.dataPageCustomIdxField;
        }
        set {
            this.dataPageCustomIdxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataPageField1")]
    public DataPageField1[] DataPageField1 {
        get {
            return this.dataPageField1Field;
        }
        set {
            this.dataPageField1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataPageField2")]
    public DataPageField2[] DataPageField2 {
        get {
            return this.dataPageField2Field;
        }
        set {
            this.dataPageField2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataPageField3")]
    public DataPageField3[] DataPageField3 {
        get {
            return this.dataPageField3Field;
        }
        set {
            this.dataPageField3Field = value;
        }
    }
}
